spring:
  application:
     name: eureka-server

security:
  headers:
    cache: false
# Configure this Discovery Server
eureka:
  server:
    enable-self-preservation: false
    response-cache-update-interval-ms: 2000
    response-cache-auto-expiration-in-seconds: 2
    
  instance:
    hostname: localhost
    nonSecurePort: 1111
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 5
    
  client:  # Not a client, don't register with yourself
    registerWithEureka: false
    fetchRegistry: false
    
server:
  port: 1111   # HTTP (Tomcat) port
