spring:
  application:
     name: zuul-server

info:
  component: Zuul Server
  
endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false

zuul:
  host:
    socket-timeout-millis: 30000
  routes:
    employee-service: 
      path: /employees/**
      serviceId: EMPLOYEE-SERVICE
      
      
server:
  port: 8765

logging:
  level:
    ROOT: INFO
    org.springframework.web: DEBUG

hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false
  
  
    
# Discovery Server Access
eureka:
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 5
    hostname: localhost
    nonSecurePort: 8765
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/
    